### ISSUE TITLE
Update crates.io

### ISSUE THREAD

**Issue by jjhbw** [atomashpolskiy/rustface#11]
Hi Andrei,

I incremented the version number and a few dependencies. 

I researched the API a bit, and I think it is most 'effort-efficient' if we move refactoring explicit SIMD support to the long term. I made a tracking issue for that (#10).

If you agree with these changes, can you run `cargo publish` on master?

**Comment by atomashpolskiy** [comment]
@jjhbw , I ran `cargo publish`, and it uploaded 0.1.1 to crates.io. However, there was this line in the output:
```
Finished dev [unoptimized + debuginfo] target(s) in 9.44 secs
   Uploading rustface v0.1.1 (file:///Users/sadpotato/git-workspace/rustface)
```
Is it OK that the build is unoptimized, or maybe I should have run the command with some additional parameters?

**Comment by jjhbw** [comment]
Great! AFAIK the build step of `cargo package` is only run to test whether the package can be built. I don't think any of the build artifacts are actually uploaded.
