### ISSUE TITLE
error: Could not compile `regex`. when trying to run test.sh

### ISSUE THREAD

**Issue by danindiana** [atomashpolskiy/rustface#13]
rustc --version
rustc 1.25.0-nightly (3f92e8d89 2018-01-14)

$./bin/test.sh /home/johnh/gits/rustfacegitmaster/rustface/examples/
./bin/test.sh: 4: ./bin/test.sh: [[: not found
./bin/test.sh: 10: ./bin/test.sh: [[: not found
Using  as the working directory
   Compiling regex v1.0.4
error[E0433]: failed to resolve. Could not find `arch` in `std`
 --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:3:10
  |
3 | use std::arch::x86_64::*;
  |          ^^^^ Could not find `arch` in `std`

error[E0433]: failed to resolve. Could not find `arch` in `std`
 --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:3:10
  |
3 | use std::arch::x86_64::*;
  |          ^^^^ Could not find `arch` in `std`

error: cannot find macro `is_x86_feature_detected!` in this scope
  --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:11:12
   |
11 |         if is_x86_feature_detected!("avx2") {
   |            ^^^^^^^^^^^^^^^^^^^^^^^

error: cannot find macro `is_x86_feature_detected!` in this scope
  --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:23:12
   |
23 |         if is_x86_feature_detected!("ssse3") {
   |            ^^^^^^^^^^^^^^^^^^^^^^^

error[E0412]: cannot find type `__m256i` in this scope
  --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:60:13
   |
60 |     vector: __m256i,
   |             ^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_set1_epi8` in this scope
  --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:67:25
   |
67 |         u8x32 { vector: _mm256_set1_epi8(n as i8) }
   |                         ^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `__m256i` in this scope
  --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:78:55
   |
78 |         let p = slice.as_ptr() as *const u8 as *const __m256i;
   |                                                       ^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_loadu_si256` in this scope
  --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:79:25
   |
79 |         u8x32 { vector: _mm256_loadu_si256(p) }
   |                         ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `__m256i` in this scope
  --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:91:55
   |
91 |         let p = slice.as_ptr() as *const u8 as *const __m256i;
   |                                                       ^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_load_si256` in this scope
  --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:92:25
   |
92 |         u8x32 { vector: _mm256_load_si256(p) }
   |                         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_shuffle_epi8` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:111:29
    |
111 |             u8x32 { vector: _mm256_shuffle_epi8(self.vector, indices.vector) }
    |                             ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_cmpeq_epi8` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:119:25
    |
119 |             let boolv = _mm256_cmpeq_epi8(self.vector, other.vector);
    |                         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_set1_epi8` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:120:24
    |
120 |             let ones = _mm256_set1_epi8(0xFF as u8 as i8);
    |                        ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_andnot_si256` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:121:29
    |
121 |             u8x32 { vector: _mm256_andnot_si256(boolv, ones) }
    |                             ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_and_si256` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:129:29
    |
129 |             u8x32 { vector: _mm256_and_si256(self.vector, other.vector) }
    |                             ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_movemask_epi8` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:137:13
    |
137 |             _mm256_movemask_epi8(self.vector) as u32
    |             ^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_permute2x128_si256` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:151:21
    |
151 |             let v = _mm256_permute2x128_si256(other.vector, self.vector, 0x21);
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_alignr_epi8` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:152:21
    |
152 |             let v = _mm256_alignr_epi8(self.vector, v, 14);
    |                     ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_permute2x128_si256` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:167:21
    |
167 |             let v = _mm256_permute2x128_si256(other.vector, self.vector, 0x21);
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_alignr_epi8` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:168:21
    |
168 |             let v = _mm256_alignr_epi8(self.vector, v, 15);
    |                     ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm256_srli_epi16` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/avx2.rs:177:29
    |
177 |             u8x32 { vector: _mm256_srli_epi16(self.vector, 4) }
    |                             ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `__m128i` in this scope
  --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:81:13
   |
81 |     vector: __m128i,
   |             ^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_set1_epi8` in this scope
  --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:88:25
   |
88 |         u8x16 { vector: _mm_set1_epi8(n as i8) }
   |                         ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_loadu_si128` in this scope
  --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:99:17
   |
99 |         let v = _mm_loadu_si128(slice.as_ptr() as *const u8 as *const __m128i);
   |                 ^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `__m128i` in this scope
  --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:99:71
   |
99 |         let v = _mm_loadu_si128(slice.as_ptr() as *const u8 as *const __m128i);
   |                                                                       ^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_load_si128` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:112:17
    |
112 |         let v = _mm_load_si128(slice.as_ptr() as *const u8 as *const __m128i);
    |                 ^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `__m128i` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:112:70
    |
112 |         let v = _mm_load_si128(slice.as_ptr() as *const u8 as *const __m128i);
    |                                                                      ^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_shuffle_epi8` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:132:29
    |
132 |             u8x16 { vector: _mm_shuffle_epi8(self.vector, indices.vector) }
    |                             ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_cmpeq_epi8` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:140:25
    |
140 |             let boolv = _mm_cmpeq_epi8(self.vector, other.vector);
    |                         ^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_set1_epi8` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:141:24
    |
141 |             let ones = _mm_set1_epi8(0xFF as u8 as i8);
    |                        ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_andnot_si128` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:142:29
    |
142 |             u8x16 { vector: _mm_andnot_si128(boolv, ones) }
    |                             ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_and_si128` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:150:29
    |
150 |             u8x16 { vector: _mm_and_si128(self.vector, other.vector) }
    |                             ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_movemask_epi8` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:158:13
    |
158 |             _mm_movemask_epi8(self.vector) as u32
    |             ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_alignr_epi8` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:166:29
    |
166 |             u8x16 { vector: _mm_alignr_epi8(self.vector, other.vector, 14) }
    |                             ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_alignr_epi8` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:174:29
    |
174 |             u8x16 { vector: _mm_alignr_epi8(self.vector, other.vector, 15) }
    |                             ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `_mm_srli_epi16` in this scope
   --> /home/johnh/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.0.4/src/vector/ssse3.rs:182:29
    |
182 |             u8x16 { vector: _mm_srli_epi16(self.vector, 4) }
    |                             ^^^^^^^^^^^^^^ not found in this scope

OS: Ubuntu 18.10 cosmic                                                                                                                                                                                          
 Kernel: x86_64 Linux 4.18.0-13-generic
 Uptime: 1h 9m
 Packages: 2393
 Shell: bash 4.4.19
 Resolution: 1920x1200
 DE: LXDE
 WM: OpenBox
 CPU: Intel Xeon W-2125 @ 8x 4.5GHz [36.0°C]
 GPU: Quadro P4000
 RAM: 2811MiB / 31821MiB

**Comment by jjhbw** [comment]
You are running a pretty old nightly rustc. Any particular reason for that? If not, you can best update to the latest stable compiler and retry.

**Comment by jjhbw** [comment]
I am closing this as the reason for this error seems clear enough to me.

**Comment by danindiana** [comment]
> You are running a pretty old nightly rustc. Any particular reason for that? If not, you can best update to the latest stable compiler and retry.

No reason except for lack of experience. Following the directions of a given tutorial my default assumption is that said instructions would lead to a more recent version of rust. I will try to find a better rust linux install and see if a more recent version of Rust corrects the issue. Thanks for your reply!
