### ISSUE TITLE
compare

### ISSUE THREAD

**Issue by tingfeng-key** [atomashpolskiy/rustface#18]
Hi, I'm learning how to use this library. How should I compare it with another graph?

**Comment by jjhbw** [comment]
Can you elaborate? I do not know what you mean by 'graph'.

**Comment by tingfeng-key** [comment]
I want to use this library for face recognition, or other image recognition, but I understand that this library can only identify faces. If you want to perform face recognition, is there any way to achieve this?

For example, I have a photo of me now, I want to use another photo to identify and contrast. This is my scene, but at the moment I don't know how to use this library to realize my idea.

**Comment by jjhbw** [comment]
That's right. This library is meant for detecting the presence and location of faces in an image. 

Actually _recognizing_ these faces as belonging to specific persons is a different task that can be performed after detection. Face recognition involves a different class of models usually based on metric learning approaches.

You can take a look at https://github.com/davidsandberg/facenet for example, or check out Dlib which features an easy-to-use implementation (http://blog.dlib.net/2017/02/high-quality-face-recognition-with-deep.html).

To start really simple, you can take a look at https://github.com/ageitgey/face_recognition. This library basically does it all for you.
