### ISSUE TITLE
error when build

### ISSUE THREAD

**Issue by sincerefly** [atomashpolskiy/rustface#4]
`error: #[target_feature] attribute must be of the form #[target_feature(..)]
   --> C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\stdsimd-0.0.3\src\x86\tbm.rs:232:1
    |
232 | #[target_feature = "+tbm"]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: #[target_feature] attribute must be of the form #[target_feature(..)]
   --> C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\stdsimd-0.0.3\src\x86\tbm.rs:244:1
    |
244 | #[target_feature = "+tbm"]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: #[target_feature] attribute must be of the form #[target_feature(..)]
   --> C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\stdsimd-0.0.3\src\x86\tbm.rs:255:1
    |
255 | #[target_feature = "+tbm"]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 750 previous errors

error: Could not compile `stdsimd`.
warning: build failed, waiting for other jobs to finish...
error: build failed`

**Comment by jjhbw** [comment]
Should be resolved now, see #9.
