### ISSUE TITLE
SIMD State and feature flag

### ISSUE THREAD

**Issue by johannesvollmer** [atomashpolskiy/rustface#40]
Hi! This library looks awesome. 
I'm a little confused. Does the stable version include SIMD?
 I'd like to use this with wasm, which does not support SIMD yet. Is it only in the nightly branch, or is there a way to deactivate it?

**Comment by jjhbw** [comment]
Which problems did you run into exactly?

I agree that the README is a bit confusing wrt SIMD. The SIMD issue is pretty old and I doubt it is relevant https://github.com/atomashpolskiy/rustface/issues/10. We don't use any explicit SIMD intrinsics and only rely on compiler autovectorisation for tight loops.

I haven't tried it, but there shouldn't be any SIMD-related obstacles to compiling this library to WASM.

**Comment by johannesvollmer** [comment]
Thanks! I appreciate your time. I did not run into any problems yet as I did not have time to incorporate this library at the moment :) If you want, I will keep you up to date about compiling it to wasm

**Comment by jjhbw** [comment]
Yes definitely sounds interesting! Let me know how it goes.
