### ISSUE TITLE
Webassembly - Assertion panics 

### ISSUE THREAD

**Issue by theduke** [atomashpolskiy/rustface#41]
When compiling to webassembly ( `--target wasm32-wasi` ) detection always results in an assertion failure.

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `826165`,
 right: `743000`', cargo/registry/src/github.com-1ecc6299db9ec823/rustface-0.1.6/src/common/image_pyramid.rs:32:9
```

**Comment by jjhbw** [comment]
Interesting. Can you post the command and toolchain version so i can repro? Did you use the example image?

**Comment by theduke** [comment]
Never mind, I was doing something wrong with the image conversion.

Working just fine.
