### ISSUE TITLE
How do you switch to Rust nightly toolchain?

### ISSUE THREAD

**Issue by rococtz** [atomashpolskiy/rustface#6]
As per my question in issue #5 I was recommended to use the nightly Rust toolchain. Any chance you can tell me where I can that from? At the moment I am using the one from the official website. Do I have to build it myself?

**Comment by danindiana** [comment]
For Linux Ubuntu 18

$rustup toolchain list

->shows a list of toolchains

then 

$cd ~/projects/need-nightly
$rustup override add nightly

activate via 

$source $HOME/.cargo/env

and check via

$rustc --version
