### ISSUE TITLE
Can I help upgrading to the stable 1.28 toolchain?

### ISSUE THREAD

**Issue by jjhbw** [atomashpolskiy/rustface#8]
Hi @atomashpolskiy ,

Cool project! Looking forward to testing it out in a side project.
However, the current dependency on `stdsimd` and an old nightly toolchain is a bit of a dealbreaker.

If I find the time, do you mind if I have a go at porting the current code to stable rustc 1.28?

You probably already put some thought into this. What is your opinion on using a crate like [faster](https://github.com/AdamNiederer/faster) to abstract away the explicit SIMD work? That way rustface stays up to date on any future improvements to Rust's SIMD intrinsics for free.

Let me know your thoughts!

**Comment by atomashpolskiy** [comment]
Hi! Thank you :) Your help would be very welcome! I don't remember why I decided to use stdsimd and I don't hold any strong opinion on switching to something else. So, basically, if this project turns out to be of interest to you, feel free to improve it as you see fit.

**Comment by jjhbw** [comment]
Great! I'll take a look.
It may take a while until you see the first commits though, you know how it goes. ;)
