### ISSUE TITLE
Moving to stable rustc 1.28

### ISSUE THREAD

**Issue by jjhbw** [atomashpolskiy/rustface#9]
Hi Andrei,

Following up on #8 , I made a little bit of progress.

Bad news: the [faster crate](https://github.com/AdamNiederer/faster) is still unstable. While it would have been very useful, having to stay on nightly is a bit of a dealbreaker for me. If I want SIMD, I'm afraid it needs to be explicit for now.

First I wanted to investigate whether explicit SIMD is still worth it with all the compiler improvements that were introduced since rustc 1.25 nightly (latest version on which the rustface master branch works, according to Travis).

To get a quick-and-dirty answer to this question, I did the following:
- I cut out all code that was incompatible with `rustc 1.28.0 stable` (that is: mostly reverting to your portable implementations of the vector math, and removing their counterparts that used explicit SIMD). See the [only_stable_features](https://github.com/atomashpolskiy/rustface/tree/only_stable_features) branch.
- I spun up a `n1-standard-4 (4 vCPUs, 15 GB memory) ` in GCP.
- I built the binaries of the `image_demo` example for master using rustc 1.25 nightly, and for my [only_stable_features](https://github.com/atomashpolskiy/rustface/tree/only_stable_features) branch using rustc 1.28 stable.
- I simply compared the runtime of these binaries from the command line, also testing the impact of the number of available Rayon threads. Note that this includes the execution time of importing the model and test image.

This yielded the following results:

| Command                                                      |     Mean [ms] |  Min…Max [ms] |
| :----------------------------------------------------------- | ------------: | ------------: |
| `RAYON_NUM_THREADS=1 ./image_demo_master_nightly_1.25.0 model/seeta_fd_frontal_v1.0.bin assets/test/scientists.jpg` | 1238.2 ± 85.0 | 1136.6…1374.6 |
| `RAYON_NUM_THREADS=1 ./image_demo_stable_1.28.0 model/seeta_fd_frontal_v1.0.bin assets/test/scientists.jpg` | 1440.8 ± 81.5 | 1322.2…1581.9 |
| `RAYON_NUM_THREADS=2 ./image_demo_master_nightly_1.25.0 model/seeta_fd_frontal_v1.0.bin assets/test/scientists.jpg` | 1242.0 ± 34.2 | 1198.7…1344.9 |
| `RAYON_NUM_THREADS=2 ./image_demo_stable_1.28.0 model/seeta_fd_frontal_v1.0.bin assets/test/scientists.jpg` | 1301.2 ± 15.4 | 1273.5…1323.7 |
| `RAYON_NUM_THREADS=3 ./image_demo_master_nightly_1.25.0 model/seeta_fd_frontal_v1.0.bin assets/test/scientists.jpg` | 1278.0 ± 16.4 | 1246.8…1311.2 |
| `RAYON_NUM_THREADS=3 ./image_demo_stable_1.28.0 model/seeta_fd_frontal_v1.0.bin assets/test/scientists.jpg` | 1328.4 ± 13.4 | 1309.0…1354.5 |

In words, that means:
'RAYON_NUM_THREADS=1 ./image_demo_master_nightly_1.25.0' ran
**1.00x faster** than 'RAYON_NUM_THREADS=2 ./image_demo_master_nightly_1.25.0'
**1.03x faster** than 'RAYON_NUM_THREADS=3 ./image_demo_master_nightly_1.25.0'
**1.05x faster** than 'RAYON_NUM_THREADS=2 ./image_demo_stable_1.28.0'
**1.07x faster** than 'RAYON_NUM_THREADS=3 ./image_demo_stable_1.28.0'
**1.16x faster** than 'RAYON_NUM_THREADS=1 ./image_demo_stable_1.28.0'

I guess this means `master` is still about ~20% faster than the `1.28` version without explicit SIMD, as could be expected. Adding more Rayon threads to `1.28` seems to compensate the difference a little bit.

As a side investigation, I also checked whether recent improvements in autovectorization may have obsoleted the need for some of your `unsafe` portable vector math functions. As expected, your functions are still the fastest:

**The `square` function:**

<img width="1135" alt="square" src="https://user-images.githubusercontent.com/12056384/44594031-5cac6d00-a7c5-11e8-89f2-af9e71050c8e.png">

**The `abs` function:**
<img width="1131" alt="abs" src="https://user-images.githubusercontent.com/12056384/44594037-61712100-a7c5-11e8-9cf2-30150f9f957d.png">

Exact code used for all the above benchmarks can be found in the README of `only_stable_features`.

Merging [only_stable_features](https://github.com/atomashpolskiy/rustface/tree/only_stable_features) would offer a quick-and-dirty way to become compatible with stable rust, but at the cost of a performance hit. For my use case, the perf hit is fine, but you may not like it for the main lib.

As mentioned in https://github.com/atomashpolskiy/rustface/issues/7#issuecomment-399665596, the new stable SIMD intrinsics may help, depending on how complete they are.
I can give refactoring a try when I find the time.

Let me know what you think.

**Comment by atomashpolskiy** [comment]
I think we might swap master and only_stable_features branches, so that the master would contain a stable, working version, and the new branch would contain the fastest possible, but unstable version, that depends on Rust nightly. Also we'll provide a note in the README, so that anyone interested in the fast version would know which branch to use.

I've added you as a collaborator and quite frankly would love to see you in this role in the long term (given that you have the interest and the time to maintain the project of course). This was my first and only experiment with Rust, and since then I've forgot most of the things that I've learnt about the language :)

**Comment by jjhbw** [comment]
Sounds great!

I will polish the [only_stable_features](https://github.com/atomashpolskiy/rustface/tree/only_stable_features) branch a bit and make a pull request to master. I'll also add the README changes you suggested.

When I find the time I'll work on a new branch with the explicit SIMD optimizations on stable Rust, most likely using your old non-portable functions as a starting point.

**Comment by atomashpolskiy** [comment]
OK! No need to make a dedicated PR, feel free to commit straight to master.

**Comment by jjhbw** [comment]
Done! See 5d21f9e6f67276f37704bee808041b11fce0866f.
I've also slightly changed the README to reflect the changes. Build is now passing. Do you want to increment the version number (on crates.io)?

I'll also close all related issues.

**Comment by atomashpolskiy** [comment]
Yeah, I guess so. Thanks a lot!
